### ISSUE TITLE
Thread activity on a single topic

### ISSUE THREAD

**Issue by jyasskin** [dontcallmedom/github-notify-ml#10]
Looking at https://lists.w3.org/Archives/Public/public-web-nfc/2015Mar/thread.html, it appears that sequences of activity on a single pull request produce a separate thread for each action. e.g. [[web-nfc] new commits pushed by kenchris Kenneth Rohde Christiansen via GitHub (Monday, 16 March)](https://lists.w3.org/Archives/Public/public-web-nfc/2015Mar/0020.html) should be a reply to [[web-nfc] Pull Request: Fix This Charter URL Anssi Kostiainen via GitHub (Monday, 16 March)](https://lists.w3.org/Archives/Public/public-web-nfc/2015Mar/0019.html)

Similarly, [Re: [mediacapture-main] Edit to address issues #73 and #96, i.e. remove file as source for MediaStream(Track)s](https://lists.w3.org/Archives/Public/public-media-capture/2014Dec/0021.html) should be a reply to [[mediacapture-main] Pull Request: Edit to address issues #73 and #96, i.e. remove file as source for MediaStream(Track)s](https://lists.w3.org/Archives/Public/public-media-capture/2014Dec/0011.html). To get those two to thread in gmail, you'll probably need to make their subjects more similar, not just add the In-Reply-To: header.

**Comment by dontcallmedom** [comment]
It's not really possible to link back from a commit to the pull request it was proposed in with the current github API; there could be more than one in any case.

I've fixed the threading for comments made on pull requests (where the In-Reply-To was wrongly set).
