### ISSUE TITLE
No threading with initial PR for comments on a PR

### ISSUE THREAD

**Issue by tidoust** [dontcallmedom/github-notify-ml#11]
I use threading in my email client to group emails together. Threading does not work with comments on a pull request though.

It may be due to the fact that the email subject is different for the pull request and for the comment on the pull request. When someone issues a pull request, the email subject is along the lines of "**Pull Request: [PR title]**". However, when someone makes a comment on the pull request, the subject becomes "**Re: [PR title]**" (thus losing the "Pull Request" prefix).

A concrete example:

* Pull request and comment on GitHub: https://github.com/w3c/presentation-api/pull/96
* Threaded view in the archives: https://lists.w3.org/Archives/Public/public-secondscreen/2015May/thread.html (PR and comment are not linked together but should be)

I do not really know what would be the most appropriate resolution here, either adjust the subject or add the right email header in the email generated by the comment to enable threading.

It may be related to #4 but it seemed different enough to create a separate issue.

**Comment by dontcallmedom** [comment]
Indeed, there is a bug there — I thought pull requests and issues shared the same id space, but they don't; I'll try to come up with a patch sometimes this week.
