### ISSUE TITLE
Comments may show up with a "None via GitHub" From field.

### ISSUE THREAD

**Issue by tidoust** [dontcallmedom/github-notify-ml#12]
Initial comment:
https://github.com/webtiming/timingobject/issues/15#issuecomment-133909002

On the mailing-list:
https://lists.w3.org/Archives/Public/public-webtiming/2015Aug/0027.html

The "From" header is "None via GitHub". It should rather be "Snarkdoof via GitHub". I haven't investigated. On top of my head, two possible reasons why this happened:

1. Snarkdoof does not have a full name: https://github.com/Snarkdoof
2. The comment was left via email reply.

**Comment by dontcallmedom** [comment]
fixed in https://github.com/dontcallmedom/github-notify-ml/commit/0c5915828a5587a52d609771c014d86860ea449c
