### ISSUE TITLE
Inaccurate repo names breaks notification silently

### ISSUE THREAD

**Issue by r12a** [dontcallmedom/github-notify-ml#34]
On 27 Sep i added `w3c/webauth` to three of our i18n notification digests, and i am only now realising that we have had no digests since then for any of those.  I believe this is because the repo name should have been `w3c/webauthn`.

Can we put in place a mechanism to alert users if a repo is incorrectly spelled, or disappears for some other reason (eg. moved or deleted, etc.)?

**Comment by dontcallmedom** [comment]
closed by https://github.com/dontcallmedom/github-notify-ml/commit/fab28864ed68f97ae534f28f93fe036337a4083d

A broken repo will no longer block sending digests for the other repos, and will be signaled as an error at the top of the digest

**Comment by r12a** [comment]
That is indeed fab. Thanks.
