### ISSUE TITLE
Missing events?

### ISSUE THREAD

**Issue by mnot** [dontcallmedom/github-notify-ml#40]
We (the QUIC WG) noticed that the digest contained far fewer issue discussions / closures than we anticipated last week (after an exceptionally active editors' meeting).

Is there any known issue / limitation that would explain that? 

If not, I'm happy to dig into it, just thought I'd ask first.

**Comment by dontcallmedom** [comment]
nothing that comes to mind - can you share the URLs of the repo, the digest and the config snippet so that I too can take a look?

**Comment by mnot** [comment]
* repo - https://github.com/quicwg/base-drafts/
* digest - https://mailarchive.ietf.org/arch/msg/quic/aqh245xIFC6rgzanV9afgNudyTU

config:

```javascript
  "quic@ietf.org": {
    "digest:sunday": {
      "repos": ["quicwg/base-drafts"],
      "topic": "QUIC Working Group Specifications",
      "eventFilter": {
        "notlabel": ["editorial"]
      }
    }
  }
```

Thanks!

**Comment by dontcallmedom** [comment]
hmm... github has a limit of [300 events](https://developer.github.com/v3/activity/events/#list-repository-events) that can be retrieved via the API.

So the bug is that your groups has been way more active than can be tracked by the system :/

**Comment by dontcallmedom** [comment]
it's actually the opposite: the [events issues API](https://developer.github.com/v3/issues/events/) is much more noisy (with mentions, subscriptions, etc).

**Comment by mnot** [comment]
Ah, OK. Perhaps we'll issue digests more often, then -- or scold editors for being so productive.

Thanks!
