### ISSUE TITLE
service marked for deprecation?

### ISSUE THREAD

**Issue by equalsJeffH** [dontcallmedom/github-notify-ml#41]
this note is appearing in _some_ auto-gen'd email sent to public-webauthn@ from github/w3c/webauthn repo:
```
**NOTE:** This service been marked for deprecation: 
https://developer.github.com/changes/2018-04-25-github-services-deprecation/

      Functionality will be removed from GitHub.com on January 31st, 2019.
```
it is not clear whether the above msg pertains to github-notify-ml or to travis-ci, or both, or something else (?)

**Comment by dontcallmedom** [comment]
afaict, this doesn't come from github-notify-ml, but rather from the [github email service](https://github.com/w3c/webauthn/settings/hooks/7797631) used to send commit log to public-webauthn (which I understand is indeed going to be turned off in the upcoming few months)

**Comment by equalsJeffH** [comment]
ok, thx for clarification. fwiw, the link to [github email services](https://github.com/w3c/webauthn/settings/hooks/7797631) 404's for me....
