### ISSUE TITLE
All of one repo and some of another

### ISSUE THREAD

**Issue by r12a** [dontcallmedom/github-notify-ml#43]
I'd like to be able to send to a mailing list a single digest for the following combination:

1. **all** of the changes to the issues in the w3c/sealreq repo, whether or not they have labels

2. issues in the csswg-drafts, html, and other repos that have the label i18n-sealreq

(sealreq is just an example)

Currently i have to set up two notifications and users receive two emails per day.

**Comment by r12a** [comment]
Any update on this?

**Comment by dontcallmedom** [comment]
I've started looking into this, but I haven't managed to carve out time recently unfortunately

**Comment by dontcallmedom** [comment]
Sorry I forgot to update the schema - that is now done, and your proposed config now passes validation, so feel free to merge it.

**Comment by r12a** [comment]
thanks @dontcallmedom  I have set one notification change so far, and will test it before setting up others. But if this works, it will be really useful. Thank you.
