### ISSUE TITLE
bug in getRepoData() ?

### ISSUE THREAD

**Issue by richsalz** [dontcallmedom/github-notify-ml#72]
```
def getRepoData(repo, token):
    url = "https://api.github.com/repos/%s" % repo
    headers = {}
    ...
```

Shouldn't `url` be "https://api.github.com/%s/repos" ?

**Comment by dontcallmedom** [comment]
`getRepoData` gets calls with `repo` of the form of `w3c/webrtc-pc`, which leads to e.g. `https://api.github.com/repos/w3c/webrtc-pc` which gives information about the said repo  (I guess the name of the function would probably be clearer as `getRepoInfo`?)
